FROM oven/bun:1.3.9 AS builder

WORKDIR /app

COPY package.json bun.lock* ./
RUN bun install --no-save --frozen-lockfile

COPY . .

RUN bun run build:storybook

FROM nginxinc/nginx-unprivileged:alpine AS production

COPY --from=builder /app/storybook-static /usr/share/nginx/html

COPY ./deployment/containers/prod/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
