name: Code Quality Checks for Pull Requests

on:
  pull_request:
    branches: [main, dev]

jobs:
  Quality_Checks:
    runs-on: ubuntu-24.04
    env:
      BUN_VERSION: "1.1.13"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun ci

      - name: Run Linter
        run: bun run lint

      - name: Run Type Check
        run: bun run typecheck:lib && bun run typecheck:showcase

      - name: Run Formatting Check
        run: bun run format:check
